import type { Translation } from "./copy.pt";

export const en: Translation = {
  nav: {
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    location: "Location",
    login: "Login",
  },
  hero: {
    title: "GAIA",
    subtitle: "Recycle, earn points, and redeem brand-sponsored vouchers. Reverse logistics that rewards people and promotes sustainable partners.",
    ctaPrimary: "Start Recycling",
    ctaSecondary: "How It Works",
  },
  about: {
    title: "About GAIA",
    subtitle: "Environmental Management and Applied Innovation driving rewards for recyclers",
    mission: "Our Mission",
    missionText:
      "Make reverse logistics simple with points that become digital vouchers, connecting consumers, brands, and the planet in a win-win loop.",
    values: "How It Works",
    valuesItems: [
      {
        title: "You Recycle",
        description: "Bring partner brand packaging to collection points",
      },
      {
        title: "Earn Points",
        description: "Accumulate points for every recycled material",
      },
      {
        title: "Redeem Vouchers",
        description: "Swap points for digital vouchers from partner brands",
      },
      {
        title: "Everyone Wins",
        description: "You save, brands engage, and the planet thanks you",
      },
    ],
  },
  services: {
    title: "How It Works",
    subtitle: "Recycling that is simple, rewarding, and brand-friendly",
    items: [
      {
        title: "1. Recycle Partner Brands",
        description:
          "Separate packaging from participating brands and take it to GAIA points",
      },
      {
        title: "2. Validate at the Collection Point",
        description: "Use your QR Code or ID to register materials at the nearest point",
      },
      {
        title: "3. Earn Points",
        description: "Get points automatically for every validated item",
      },
      {
        title: "4. Redeem Vouchers",
        description:
          "Redeem digital vouchers for products and perks from sponsoring brands",
      },
    ],
  },
  contact: {
    title: "Get In Touch",
    subtitle: "We're ready to help you",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    submit: "Send message",
    sending: "Sending...",
    success: "Message sent successfully!",
    error: "Error sending message. Please try again.",
  },
  location: {
    title: "Our Location",
    subtitle: "Visit us or get in touch",
    address: "Address",
    phone: "Phone",
    openMaps: "Open in Google Maps",
  },
  login: {
    title: "Welcome back",
    subtitle: "Sign in with your credentials",
    email: "Email",
    password: "Password",
    submit: "Sign In",
    loggingIn: "Signing in...",
    createAccount: "Create account",
    forgotPassword: "Forgot password",
    success: "Login successful!",
    error: "Invalid credentials. Please try again.",
  },
  footer: {
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
    followUs: "Follow us",
  },
  common: {
    loading: "Loading...",
    learnMore: "Learn more",
    getStarted: "Get Started",
    readMore: "Read more",
  },
  dashboard: {
    welcome: "Welcome back",
    points: "Your Points",
    totalRecycled: "Total Recycled",
    availableProducts: "Available Vouchers",
    recentActivity: "Recent Activity",
    quickActions: "Quick Actions",
    recycleNow: "Recycle Now",
    browseStore: "Browse Store",
    findCollection: "Collection Points",
    viewHistory: "View History",
  },
  recycle: {
    title: "Recycle",
    subtitle: "Earn points for every recycled material",
    howTo: "How to Recycle",
    step1: "Separate packaging from partner products",
    step2: "Take to the nearest collection point",
    step3: "Present your QR Code or ID",
    step4: "Earn points automatically",
    materials: "Accepted Materials",
    plastic: "Plastic",
    paper: "Paper/Cardboard",
    glass: "Glass",
    metal: "Metal/Aluminum",
  },
  store: {
    title: "Rewards Store",
    subtitle: "Redeem your points for brand-sponsored vouchers",
    yourPoints: "Your Points",
    pointsNeeded: "points needed",
    redeem: "Redeem",
    insufficientPoints: "Insufficient points",
    categories: "Categories",
    all: "All",
    featured: "Featured",
  },
  history: {
    title: "History",
    subtitle: "Your recycling and redemptions",
    recycling: "Recycling",
    redemptions: "Redemptions",
    date: "Date",
    points: "Points",
    material: "Material",
    product: "Voucher",
    status: "Status",
  },
  partners: {
    title: "Partner Brands",
    subtitle: "Companies participating in reverse logistics",
    joinProgram: "Join the Program",
  },
};
